# Generated by Django 3.1.2 on 2020-10-29 19:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tutorial_image',
            field=cloudinary.models.CloudinaryField(default='test', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
